# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrousuario():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrousuario(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1656, 804)
    self.driver.find_element(By.CSS_SELECTOR, ".user-message").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".login .form-title").text == "Entrar ou Criar Conta"
    self.driver.find_element(By.ID, "login-form-email").click()
    self.driver.find_element(By.ID, "login-form-email").send_keys("test001@testepersonalizado.com")
    self.driver.find_element(By.ID, "login-btn-toggle").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".form-title-container:nth-child(1) > .form-title").text == "Criar Conta"
    self.driver.find_element(By.ID, "registration-form-fname").click()
    self.driver.find_element(By.ID, "registration-form-fname").send_keys("Testonildo")
    self.driver.find_element(By.ID, "registration-form-lname").click()
    self.driver.find_element(By.ID, "registration-form-lname").send_keys("Da Silva")
    self.driver.find_element(By.ID, "registration-form-bdate").click()
    self.driver.find_element(By.ID, "registration-form-bdate").send_keys("01/01/1999")
    self.driver.find_element(By.ID, "registration-form-gender").click()
    dropdown = self.driver.find_element(By.ID, "registration-form-gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Masculino']").click()
    self.driver.find_element(By.ID, "registration-form-cpf").click()
    self.driver.find_element(By.ID, "registration-form-cpf").send_keys("000.111.222-33")
    self.driver.find_element(By.ID, "registration-form-phone").click()
    self.driver.find_element(By.ID, "registration-form-phone").send_keys("+5521999998888")
    self.driver.find_element(By.ID, "registration-form-email-confirm").click()
    self.driver.find_element(By.ID, "registration-form-email-confirm").send_keys("test001@testepersonalizado.com")
    self.driver.find_element(By.ID, "registration-form-password").click()
    self.driver.find_element(By.ID, "registration-form-password").send_keys("amotestes10!A")
    self.driver.find_element(By.ID, "registration-form-password-confirm").click()
    self.driver.find_element(By.ID, "registration-form-password-confirm").send_keys("amotestes10!A")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-control-label").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(16)").text == "CRIAR CONTA"
    self.driver.find_element(By.CSS_SELECTOR, ".it_header--logo").click()
  
