# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestComprarpelowhatsapp():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_comprarpelowhatsapp(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1656, 804)
    assert self.driver.find_element(By.CSS_SELECTOR, ".hidden-sm-down li:nth-child(1) .it__above--text > span").text == "COMPRE PELO WHATSAPP"
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".hidden-sm-down li:nth-child(1) .it__above--text > span").click()
    self.vars["win9008"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9008"])
    assert self.driver.find_element(By.CSS_SELECTOR, ".\\_9vd6:nth-child(1) > .\\_9vd5:nth-child(2)").text == "Cacau Show Delivery"
    assert self.driver.find_element(By.CSS_SELECTOR, "#action-button > .\\_advp").text == "Iniciar conversa"
  
