# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestComprarproduto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_comprarproduto(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1656, 804)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Caixa de Bombons Sortidos Angel")
    self.driver.find_element(By.CSS_SELECTOR, "#product-0 .name").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".product-name").text == "Caixa de Bombons Sortidos Angel Coração 290g"
    assert self.driver.find_element(By.CSS_SELECTOR, ".prices .it__shelf__discountPrice > span:nth-child(2)").text == "99.99"
    assert self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart").text == "ADICIONAR AO CARRINHO"
    self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".it__minicart .minicart-icon").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".page-title").text == "Carrinho de Compra"
    assert self.driver.find_element(By.CSS_SELECTOR, ".it__minicart .minicart-quantity").text == "1"
    assert self.driver.find_element(By.CSS_SELECTOR, ".line-item-name").text == "Caixa de Bombons Sortidos Angel Coração 290g"
    assert self.driver.find_element(By.CSS_SELECTOR, ".line-item-total-price-amount").text == "R$99.99"
    assert self.driver.find_element(By.CSS_SELECTOR, ".checkout-btn").text == "FINALIZAR COMPRA"
    self.driver.find_element(By.CSS_SELECTOR, ".hidden-md-down > .remove-product").click()
    assert self.driver.find_element(By.ID, "removeProductLineItemModal").text == "Remover produto ?"
    self.driver.find_element(By.CSS_SELECTOR, ".cart-delete-confirmation-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".it_header--logo").click()
  
